[package]
name = "rust"
version = "0.1.0"
edition = "2021"

[dependencies]

[profile.release]
strip = true

[profile.dev]
opt-level = 1
overflow-checks = false
incremental = true

[profile.dev.package."*"]
opt-level = 3
overflow-checks = false
incremental = true
